# Generated by Django 5.0.7 on 2024-08-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ordemservico_data_servico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='foto',
        ),
    ]
