# Generated by Django 5.0.7 on 2024-08-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ativo'), (0, 'Desativado')], default=1),
        ),
    ]
