# Generated by Django 5.0.7 on 2024-08-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.BooleanField(choices=[(1, 'Ativo'), (0, 'Desativado')], default=True),
        ),
    ]
